### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by flywukong** [valerytschopp/python-radosgw-admin#14]
I use the command " python  radosgw-admin-example.py  --hostname=172.16.154.*  -a C3H********** -s gEl4uaoGWDd3oH78kCo***********
" but I get message"ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)“. I have cofigured the ssl for my apache . 
How can I fix the problem?

**Comment by valerytschopp** [comment]
You have to specify the `--hostname` parameter with the fully qualified host name (e.g. `-H radosgw.example.org`), not the IP address. Otherwise the SSL certificate can not be verified.

Additionally, I don't think `172.16.154.*` is a valid IP address...
