### ISSUE TITLE
Python3 Incompatibility

### ISSUE THREAD

**Issue by noah-mercado** [valerytschopp/python-radosgw-admin#21]
## Issue
Line 360 of `connection.py` makes this library only work with Python 2 due to the it's check for type `unicode` which was renamed to `str` in Python 3. Could we update this please?

## Error
```
  File "/Users/c81298/.local/share/virtualenvs/symphony-s3-xs1SLCJ5/lib/python3.6/site-packages/radosgw/connection.py", line 360, in get_buckets
    if isinstance(body_json[0], unicode) or isinstance(body_json[0], str):
NameError: name 'unicode' is not defined
```

**Comment by valerytschopp** [comment]
New version 1.6.0 of the library support Python3 now.
