### ISSUE TITLE
Create bucket operation

### ISSUE THREAD

**Issue by Wilm0r** [valerytschopp/python-radosgw-admin#26]
I noticed this library can create users and it can do various admin operations on buckets, it can't create buckets. Also I noticed this operation is not on https://docs.ceph.com/docs/nautilus/radosgw/adminops/ . Likely it's not there because it's part of the standard S3 API already which makes sense.

For completeness though, would this still be a useful call to add?

**Comment by Wilm0r** [comment]
Realised this is a pretty simple function one can add to their code when needed, yet kind of hairy for the admin module to include since it needs to make a call outside `admin_path`. So my function creates a one-off admin connection with that variable overridden:

```python
def create_bucket(bucket_name):
        adm = radosgw.connection.RadosGWAdminConnection(admin_path="/", **rgw_flags)
        response = adm.make_request('PUT', path='/%s/' % bucket_name, query_params=None)
        return response.code in (200, 409)
```

**Comment by valerytschopp** [comment]
It is not a gap in the Ceph admin API, it is the difference between the standard S3 API (e.g. PUT /bucketName) and the non standardized admin S3 API.

I will not add a standard S3 API, like create-bucket to the Ceph radosgw admin API. 
Like you describe above, you can easily implement a create_bucket method in your code.
