### ISSUE TITLE
NameError: name 'query' is not defined

### ISSUE THREAD

**Issue by twichy** [valerytschopp/python-radosgw-admin#9]
There is an error in: python-radosgw-admin/radosgw/connection.py

In line 101 you are using the variable "query" which does not exist..
I think you forgot to init this variable in line 97:
urlencode(query_params)
should be:
query = urlencode(query_params)

Not going to bother creating a new pull request , i think it's a hot fix sort of bug

**Comment by valerytschopp** [comment]
Thanks @twichy 

The fix is pushed now.

**Comment by valerytschopp** [comment]
commit d64fa4f99c496631858f20adfe3bedfa8b98538d
